name: Docker Image CI

on:
  push:
    branches: [main]	

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
              submodules: "true"
    - run: |
            cd dockerfileSubmodule
            git checkout v1.0.0 
            cd ../
    - name: Build the Docker image
      run: docker build -f dockerfileSubmodule/Dockerfile -t dockerpy .
