name: Docker Image CI

on:
  push:
    branches: [main]	

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
              submodules: "recursive"
    - run: ls
    - run: ls dockerfileSubmodule
    - name: Build the Docker image
      run: docker build -f ./dockerfileSubmodule -t dockerpy .
