name: Docker Image CI

on:
  push:
    branches: [main]	

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: ls
    - run: cd dockerfileSubmodule
    - name: Build the Docker image
      run: docker build -t dockerpy ./dockerfileSubmodule
